### ISSUE TITLE
AutoVTF Won't Open

### ISSUE THREAD

**Issue by CatEarsMesa** [NvC-DmN-CH/AutoVTF#1]
Even with .NET 8 installed and it no no wanna.

P.S. Pleb eats children

**Comment by NvC-DmN-CH** [comment]
Can someone else confirm this?

**Comment by CatEarsMesa** [comment]
> Are you on windows 10? Does it show any errors on startup

I'm on windows 10 and nothing opens, no error window or anything

**Comment by NvC-DmN-CH** [comment]
> > Are you on windows 10? Does it show any errors on startup
> 
> I'm on windows 10 and nothing opens, no error window or anything

Okay try the newest release, it's a 64 bit build, apparently it should be fixed now

**Comment by CatEarsMesa** [comment]
> > > Are you on windows 10? Does it show any errors on startup
> > 
> > 
> > I'm on windows 10 and nothing opens, no error window or anything
> 
> Okay try the newest release, it's a 64 bit build, apparently it should be fixed now

Thanks! That fixed it!

**Comment by NvC-DmN-CH** [comment]
Strange, I made it to build as a 32bit application, but apparently some part of the program still is set as 64 bit or something. So since idk what I'm doing the program is 64 bit now, glad that this actually helped lol
