### ISSUE TITLE
PSD to VTF conversion doesn't retain the Alpha channel

### ISSUE THREAD

**Issue by DBONKA** [NvC-DmN-CH/AutoVTF#10]
![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/38439779/a07ef86a-d02f-494b-8a6f-f41b1eaaf385)
![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/38439779/04e85ffb-5c3f-496a-9164-00be49f93615)
![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/38439779/b578cb70-1e08-4bfa-885a-a264354c2454)
When I convert PSD into VTF, the Alpha Channel is discarded. Lossless, Compressed, Advanced (RGBA8888) - it doesn't matter. But if I save PSD as TGA using photoshop, and then convert TGA to VTF using AutoVTF, the Alpha channel remains.

**Comment by NvC-DmN-CH** [comment]
Noted, will try to fix this asap

**Comment by DBONKA** [comment]
Still doesn't work. 

If I try it with a shape on a transparent background, the alpha channel gets created when converted to VTF.

 But, in my case, there's no transparency at all, the image is fully opaque. I need the Alpha for reflectivity. In this case, it makes the Alpha channel fully white when converted. Because, I assume, it doesn't see any transparency.

My PS version is 21.1.1

I uploaded a .PSD for the test here: https://github.com/DBONKA/test/blob/main/AlphaTest.psd

If you import it using VTFEdit, there will be a black alpha channel with 4 white text strings
If you import it using AutoVTF, the alpha channel will be fully white

**Comment by NvC-DmN-CH** [comment]
> Still doesn't work.
> 
> If I try it with a shape on a transparent background, the alpha channel gets created when converted to VTF.
> 
> But, in my case, there's no transparency at all, the image is fully opaque. I need the Alpha for reflectivity. In this case, it makes the Alpha channel fully white when converted. Because, I assume, it doesn't see any transparency.
> 
> My PS version is 21.1.1
> 
> I uploaded a .PSD for the test here: https://github.com/DBONKA/test/blob/main/AlphaTest.psd
> 
> If you import it using VTFEdit, there will be a black alpha channel with 5 white text strings If you import it using AutoVTF, the alpha channel will be fully white
> 
> You can check the .VTF alpha channel using VTFEdit by: View - Channel - A

Hmm...
Okay, Photoshop version doesn't seem to matter here.
The alpha channel seems to take effect only when there is 1 layer and it's the special Background layer.
![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/82bdec7d-def9-4ee5-af80-8e97911a726d)

I assume this is some kind of bug in ImageMagick, or... Okay I might be able to handle this case somehow, I'll try tomorrow though, sorry

**Comment by NvC-DmN-CH** [comment]
Okay I made PSD -> VTF use VTFCmd's built in PSD reader

It should hopefully work fine now. Download the new 1.2.3 version please
