### ISSUE TITLE
.VTF loses the Alpha channel when updated from .PSD with the same name

### ISSUE THREAD

**Issue by DBONKA** [NvC-DmN-CH/AutoVTF#12]
When .PSD is converted and .vtf is created for the first time - .vtf has the correct Alpha channel (the bug was fixed)

But, when you convert .PSD again (even if it's the exact same .PSD with 0 changes) and the .vtf "updates" - .vtf's Alpha will be fully white

So because of this bug, you can't make changes to already existing .VTFs, you have to constantly delete .VTF files so they get created with the correct Alpha

**Comment by DBONKA** [comment]
> Are you doing it by using an alpha channel like this: ![image](https://private-user-images.githubusercontent.com/56874047/340715745-bc86fec3-bf11-47e8-b3cc-4a947c1124d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjEyNTAsIm5iZiI6MTcxODcyMDk1MCwicGF0aCI6Ii81Njg3NDA0Ny8zNDA3MTU3NDUtYmM4NmZlYzMtYmYxMS00N2U4LWIzY2MtNGE5NDdjMTEyNGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE0MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlODllMTBiYjliNGQ0NWY4YzQyZDBhMGY0Y2I5MTZlYWZjMDNkNmJlMmY4M2YwMGRlNjdhOTY0NmEwODgxY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6HLaAfsJAENX2YYW72i5pC1ksh2OnAMYWAdTQPVPVTQ)
> 
> or transparency like this: ![image](https://private-user-images.githubusercontent.com/56874047/340715504-21442346-c203-418a-80dc-2d3262ccab75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjEyNTAsIm5iZiI6MTcxODcyMDk1MCwicGF0aCI6Ii81Njg3NDA0Ny8zNDA3MTU1MDQtMjE0NDIzNDYtYzIwMy00MThhLTgwZGMtMmQzMjYyY2NhYjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE0MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNzVlZjkwYmUyOWYxNzZjNDYyY2EyMzRkZmY2YTE5NTBlNzNlZjZkOWFmOGYyYmQzZjI0ZWY5MmZmNDVkZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uSrFWSGy7NwBIqhR_6COTfZTDlIKCCdj92Gf7jmCY24)

The first way

**Comment by NvC-DmN-CH** [comment]
> When .PSD is converted and .vtf is created for the first time - .vtf has the correct Alpha channel (the bug was fixed)
> 
> But, when you convert .PSD again (even if it's the exact same .PSD with 0 changes) and the .vtf "updates" - .vtf's Alpha will be fully white
> 
> So because of this bug, you can't make changes to already existing .VTFs, you have to constantly delete .VTF files so they get created with the correct Alpha

Huh, weird... I just tried and there was no alpha channel in the VTF not even in the first time... Oh I hate dealing with proprietary image formats  lmao

**Comment by NvC-DmN-CH** [comment]
Ok I think I got it, hopefully-

A new version may come in a bit

**Comment by NvC-DmN-CH** [comment]
I just pushed 1.2.5

Try the newest version please
