### ISSUE TITLE
Windows with errors

### ISSUE THREAD

**Issue by MARK2580** [NvC-DmN-CH/AutoVTF#4]
Hello. An interesting program, but for some reason I get 2-3 errors every time a saving request window appears in Photoshop (for example, tga bit depth or png compression).
![scr_13_05_2024_16_04_08](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/8a8eb221-878c-4315-a0d2-bf2318aae3e9)

p.s. - PSD is not the best format for converting to vtf, once I created a grass texture (for displacement, not a model) and for a long time I could not understand why there were so many graphic artifacts around the blades of grass, only when I saved it as a regular png I got a normal vtf file.

**Comment by NvC-DmN-CH** [comment]
Oh wow, hmmm

I, honestly have no idea why it wouldn't be able to read the TGA
Basically, when converting from PSD to VTF, it happens like this: PSD -> TGA -> VTF

I just tried in my photoshop (CS6) and it really did error out for me, which I'm glad because it means I can figure out what exactly is going on locally... Okay that's 1 thing slightly closer to fixing

I will look into it.


About the p.s: Sorry yeah, I rely on ImageMagick which is the best library for reading PSD files to my knowledge, and they can't support all PSD features especially if they are new.

Try to not use the newest photoshop features, or use an older photoshop. I use Photoshop CS6 and everything has converted 100% accurately so far. I'll make a notice about that in the main page

**Comment by NvC-DmN-CH** [comment]
Can you provide me with the Photoshop file which produced a wrong output, and also say which Photoshop you used?

**Comment by MARK2580** [comment]
> I'm curious, can you provide me with the PSD file which produced a wrong output, and also say which Photoshop you used?

**Preface:**
_It was a very long time ago, in 2018, when I was building a large-scale map with a yacht, I planned to build an additional island with vegetation there, but firstly, the grass greatly reduced performance, and secondly, it disappeared a couple of meters from the player, which is why I and abandoned this idea._

In short, I assembled a texture for grass (vbsp) in Photoshop, knowing that VTFCmd recognizes PSD files, I was too lazy to convert everything into png or tga and fed the PSD to VTFCmd. As a result, I got a frame of artifacts around each blade of grass, as if they had been cut out crookedly. For a long time I could not understand what the problem was, I tried to create a VTF using VTFEdit, but I got the same result. In the end, I saved a regular PNG file and the problem disappeared (well, almost).

Unfortunately, I cannot completely repeat what happened then, I lost the vbsp file, and by some miracle the PSD remained. But still, even in Hammer, the difference is visible. At that time, I think I was using Photoshop CS6.

![scr_14_05_2024_16_30_41](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/dd6707e7-e4ae-4496-a7e7-a5f9b7fc9cbb)
![scr_14_05_2024_16_31_33](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/c3a5b77f-c495-4abc-84e0-a7a9588e2aea)
[PSD.zip](https://github.com/NvC-DmN-CH/AutoVTF/files/15309121/PSD.zip)

**Comment by NvC-DmN-CH** [comment]
Hmm

interesting.. VTFCmd doesn't recognize PSD files btw. I use ImageMagick to convert PSD to TGA, and feed that into it.

ImageMagick says that it can't convert a few things properly, maybe it's those? I really don't know what could be causing the difference.

All I know is that I've never used those. Hovering over them it says "Layer Thumbnail"

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/0cddac34-17d6-4227-9154-0fb1a13b23b9)

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/e9d624ae-f1ca-4626-810b-57b50aaa70ae)


Sorry, I also wish we wouldn't have to worry about differences, it's an ImageMagick issue so I'm helpless.. You could make an issue about your specific psd file here: https://github.com/dlemstra/Magick.NET/issues

**Comment by Sherlock2004** [comment]
> interesting.. VTFCmd doesn't recognize PSD files btw. I use ImageMagick to convert PSD to TGA, and feed that into it.

VTFCmd and VTFEdit support the PSD format, although this is not documented. Try it yourself.

https://github.com/NvC-DmN-CH/AutoVTF/assets/88171363/d7a335a3-7c6b-45d8-a0bc-8b63d8e33025

**Comment by NvC-DmN-CH** [comment]
> > interesting.. VTFCmd doesn't recognize PSD files btw. I use ImageMagick to convert PSD to TGA, and feed that into it.
> 
> VTFCmd and VTFEdit support the PSD format, although this is not documented. Try it yourself.
> NVIDIA_Share_VrYPYrn7GK.mp4
> 
> P.S - As you can see, this program is of little use to me personally; I have long ago had buttons configured that, in 2 clicks, allow me to convert any file under the cursor or even a folder or folder with subfolders into VTF. But sometimes there are actually cases when you edit a texture for a long time and persistently, and even these two clicks take quite a lot of time to check the result. Unfortunately, no one has made a VTF plugin for x64 Photoshop. This is where I find this program interesting. 😁

Oh damn I see. Does the difference in exporting the psd happen with vtfedit?

**Comment by MykhailKozak** [comment]
> > I'm curious, can you provide me with the PSD file which produced a wrong output, and also say which Photoshop you used?
> 
> **Preface:** _It was a very long time ago, in 2018, when I was building a large-scale map with a yacht, I planned to build an additional island with vegetation there, but firstly, the grass greatly reduced performance, and secondly, it disappeared a couple of meters from the player, which is why I and abandoned this idea._
> 
> In short, I assembled a texture for grass (vbsp) in Photoshop, knowing that VTFCmd recognizes PSD files, I was too lazy to convert everything into png or tga and fed the PSD to VTFCmd. As a result, I got a frame of artifacts around each blade of grass, as if they had been cut out crookedly. For a long time I could not understand what the problem was, I tried to create a VTF using VTFEdit, but I got the same result. In the end, I saved a regular PNG file and the problem disappeared (well, almost).
> 

This matting is happening because there's no actual color data in the transparency, so it defaults to filling the background with a color typically white, but this is more a workflow error and not a software problem. This is probably more pronounced on the PSD because of how magick interpolates this during conversion. The best thing to do is to fill the background and use an actual alpha channel instead of layer transparency. What I typically do is content aware fill the background in and darken to prevent haloing edges on mips like so. 
![gtav_grass](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/04e9ea68-e5ee-4276-bd0c-d26ae5f4eaee)
![ps](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/7e97d399-8d28-41eb-a419-b6352505b38f)

**Comment by MARK2580** [comment]
At that moment, I simply saved the final version in png format and that’s it, because... Photoshop works very strangely with tga and may stubbornly refuse to save the alpha channel, no matter how hard you try.

**Comment by NvC-DmN-CH** [comment]
> > Oh damn I see. Does the difference in exporting the psd happen with vtfedit?
> 
> I did not understand the question 🙄

I'm sorry, I meant VTFCmd, I'll say it again but properly this time:

Does the exporting difference also happen when using VTFCmd to convert the PSD to VTF?

**Comment by NvC-DmN-CH** [comment]
> > interesting.. VTFCmd doesn't recognize PSD files btw. I use ImageMagick to convert PSD to TGA, and feed that into it.
> 
> VTFCmd and VTFEdit support the PSD format, although this is not documented. Try it yourself.
> NVIDIA_Share_VrYPYrn7GK.mp4
> 
> P.S - As you can see, this program is of little use to me personally; I have long ago had buttons configured that, in 2 clicks, allow me to convert any file under the cursor or even a folder or folder with subfolders into VTF. But sometimes there are actually cases when you edit a texture for a long time and persistently, and even these two clicks take quite a lot of time to check the result. Unfortunately, no one has made a VTF plugin for x64 Photoshop. This is where I find this program interesting. 😁

I think I should say it here as well: I did some research regarding VTFCmd's PSD capabilities https://github.com/NvC-DmN-CH/AutoVTF/issues/7#issuecomment-2126148262

**Comment by MARK2580** [comment]
> Does the exporting difference also happen when using VTFCmd to convert the PSD to VTF? Or does it only happen when using AutoVTF to convert a PSD to VTF?

AutoVTF converts well, but not perfectly. I see small artifacts that are bright green when compared to the psd-png-vtfcmd version.  
![scr_23_05_2024_08_48_17](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/ac5b0eb0-305c-4da3-ac34-1f5c0b5b9b1c)


![scr_23_05_2024_08_43_58](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/bae1cd8c-d849-47cb-a726-5011cb6b4e70)
![scr_23_05_2024_08_44_30](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/3320e223-b9c6-4aa8-81f8-f60bc50f73f4)
![scr_23_05_2024_08_45_36](https://github.com/NvC-DmN-CH/AutoVTF/assets/11617079/ae6b5083-5a2b-4237-b19e-d0351159a240)

**Comment by NvC-DmN-CH** [comment]
I see

**Comment by NvC-DmN-CH** [comment]
> > Does the exporting difference also happen when using VTFCmd to convert the PSD to VTF? Or does it only happen when using AutoVTF to convert a PSD to VTF?
> 
> AutoVTF converts well, but not perfectly. I see small artifacts that are bright green when compared to the psd-png-vtfcmd version.
> xnviewmp_Ld3h6NjUSa.mp4
> 
> ![scr_23_05_2024_08_43_58](https://private-user-images.githubusercontent.com/11617079/333053848-bae1cd8c-d849-47cb-a726-5011cb6b4e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODU2MTksIm5iZiI6MTcxNzU4NTMxOSwicGF0aCI6Ii8xMTYxNzA3OS8zMzMwNTM4NDgtYmFlMWNkOGMtZDg0OS00N2NiLWE3MjYtNTAxMWNiNmI0ZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NGY0ZTI2NGI4OGExMmI4NjkxMmRjNDU0Njk1MzIzOTkzOGYzY2JhNmI4YTI3MDVlNmNhMjg2YjFjNzUxYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aaqshgpRsSqQRJZMg8VBg-IBbFpVgw0naCxzCA5nlvk) ![scr_23_05_2024_08_44_30](https://private-user-images.githubusercontent.com/11617079/333053860-3320e223-b9c6-4aa8-81f8-f60bc50f73f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODU2MTksIm5iZiI6MTcxNzU4NTMxOSwicGF0aCI6Ii8xMTYxNzA3OS8zMzMwNTM4NjAtMzMyMGUyMjMtYjljNi00YWE4LTgxZjgtZjYwYmM1MGY3M2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZWQwMTRiZjczOTg3ZTJhYjk4YzAwNmExZjY3YTdhOTI0MzRlOWUzZTdhNTFkZjIzMWQwZDg3ZjI3NmZkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4c8w97Q6H1FtlC4yheQ0wJsVgfZTR1XyIbKrB6nKCk) ![scr_23_05_2024_08_45_36](https://private-user-images.githubusercontent.com/11617079/333053864-ae6b5083-5a2b-4237-b19e-d0351159a240.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODU2MTksIm5iZiI6MTcxNzU4NTMxOSwicGF0aCI6Ii8xMTYxNzA3OS8zMzMwNTM4NjQtYWU2YjUwODMtNWEyYi00MjM3LWIxOWUtZDAzNTExNTlhMjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDExMDE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMDQyMTU5ZWU1MDFhMGI1ZjZjZWI0YzNjZDBlZGMwNDk2MDNmZTE0NjRkODRlOTc4MGY1Njc2MzYxNjIxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vx224IjOc8HReu-sZZRP1dw-vZEjxlOwtxX68Ju5Diw)


The problem should be resolved! I just uploaded a new version (1.2.2) try it and report back if you still encounter the problem please

**Comment by MARK2580** [comment]
> actually, try 1.2.3

I have now downloaded version 1.2.3 and to be honest I am confused, autovtf conversion is the same as how I would convert psd via vtfcmd, because... with a thick frame around it, and not as it was in the test earlier with small green artifacts 🤨
