### ISSUE TITLE
When dragging more than one image to convert it only converts one.

### ISSUE THREAD

**Issue by CatEarsMesa** [NvC-DmN-CH/AutoVTF#5]
When dragging and dropping more than one image, it only converts the first image! Not necessarily a bug but it would be a cool feature to add mayhaps.

**Comment by NvC-DmN-CH** [comment]
oh, this would actually be so useful for bulk converting.

**Comment by NvC-DmN-CH** [comment]
okay i just implemented it

**Comment by NvC-DmN-CH** [comment]
Version 1.2

Support for bulk converting by drag and dropping multiple files.
When making a VMT, `$basetexture` now has quotes around it (it worked fine without quotes, but the lack of quotes seemed to confuse some users)
