### ISSUE TITLE
PSD does not retain alpha channel on conversion

### ISSUE THREAD

**Issue by MykhailKozak** [NvC-DmN-CH/AutoVTF#7]
The PSD to TGA conversion step does not retain a PSDs alpha channel. Whether that's a problem of ImageMagick not supporting the alpha channels, or the TGA not being exported as 32 bit with alpha, I don't know. But this would be fixed if use is made of VTFCmds PSD support regardless. 

_Originally posted by @MykhailKozak in https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123620496_

**Comment by NvC-DmN-CH** [comment]
> The PSD to TGA conversion step does not retain a PSDs alpha channel. Whether that's a problem of ImageMagick not supporting the alpha channels, or the TGA not being exported as 32 bit with alpha, I don't know. But this would be fixed if use is made of VTFCmds PSD support regardless.
> 
> _Originally posted by @MykhailKozak in [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123620496)_


Oh wow, I just tried it and I don't know how I didn't catch this bug. I think it's an issue which I can actually fix, and I'll try to do it now.

Also wait, I'm confused here when you said this "But this would be fixed if use is made of VTFCmds PSD support regardless" don't you mean "AutoVTF's PSD support" ?

**Comment by MykhailKozak** [comment]
> > The PSD to TGA conversion step does not retain a PSDs alpha channel. Whether that's a problem of ImageMagick not supporting the alpha channels, or the TGA not being exported as 32 bit with alpha, I don't know. But this would be fixed if use is made of VTFCmds PSD support regardless.
> > _Originally posted by @MykhailKozak in [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123620496)_
> 
> Oh wow, I just tried it and I don't know how I didn't catch this bug. I think it's an issue which I can actually fix, and I'll try to fix it now. Thank you for reporting.
> 
> Also wait, I'm confused here when you said this "But this would be fixed if use is made of VTFCmd's PSD support regardless" don't you mean "AutoVTF's PSD support" ?

As was explained here https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2119045633
VTFCmd does have undocumented PSD support, I confirmed this on old VTFEdit by selecting PSD with All Formats

**Comment by NvC-DmN-CH** [comment]
> > > The PSD to TGA conversion step does not retain a PSDs alpha channel. Whether that's a problem of ImageMagick not supporting the alpha channels, or the TGA not being exported as 32 bit with alpha, I don't know. But this would be fixed if use is made of VTFCmds PSD support regardless.
> > > _Originally posted by @MykhailKozak in [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123620496)_
> > 
> > 
> > Oh wow, I just tried it and I don't know how I didn't catch this bug. I think it's an issue which I can actually fix, and I'll try to fix it now. Thank you for reporting.
> > Also wait, I'm confused here when you said this "But this would be fixed if use is made of VTFCmd's PSD support regardless" don't you mean "AutoVTF's PSD support" ?
> 
> As was explained here [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2119045633) VTFCmd does have undocumented PSD support, I confirmed this on old VTFEdit by selecting PSD with All Formats

Oh interesting. Okay, I did some testing and here's what happens:

I made this in Photoshop:

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/88ed6cf6-f40c-401e-a1ce-f21d4ada318e)

Saved it as 32bits/pixel TGA:

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/e4529e2c-6d49-4a88-b3c3-43fe1fea930d)

And when I import it back into Photoshop, I saw that the TGA itself just doesn't have any alpha information:

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/e98b98cb-3f95-433b-974b-6210904bda85)

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/ff0ab7e3-265c-426a-95db-7b6c7e7483f5)

Confirms what [MARK2580](https://github.com/MARK2580) said here: https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123696810


---

But, If I go back and don't save it as a TGA, but as a PSD instead:

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/bde40fad-d1aa-44a1-92b0-2ddca4f6b5f1)

And then feed that PSD into AutoVTF:

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/ce1b3bc3-9286-4dd2-b89c-a6612f22fff2)

Then, in the VTF it actually has alpha

![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/526478a8-0559-4dc3-9e92-af0b89c5d092)

It's an issue with Photoshop *itself* somehow not being able to keep alpha when exporting to TGA... Which is very weird, and it seems like you shouldn't have a problem, but you do though. Can you describe your process like I did?

**Comment by NvC-DmN-CH** [comment]
Removing bug label for now until things are cleared up

**Comment by NvC-DmN-CH** [comment]
On a side note, I saw that VTFCmd supports PSD because it relies on DevIL, which supports it:
https://openil.sourceforge.net/features.php

It's been last updated in 2017 though
![image](https://github.com/NvC-DmN-CH/AutoVTF/assets/56874047/ea0685ef-80aa-4063-b7f5-12f076b2d5a6)

It would be easier to let DevIL do the work but ImageMagick is being actively maintained, so I think it's better to stick with it.

**Comment by MykhailKozak** [comment]
> > > > The PSD to TGA conversion step does not retain a PSDs alpha channel. Whether that's a problem of ImageMagick not supporting the alpha channels, or the TGA not being exported as 32 bit with alpha, I don't know. But this would be fixed if use is made of VTFCmds PSD support regardless.
> > > > _Originally posted by @MykhailKozak in [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123620496)_
> > > 
> > > 
> > > Oh wow, I just tried it and I don't know how I didn't catch this bug. I think it's an issue which I can actually fix, and I'll try to fix it now. Thank you for reporting.
> > > Also wait, I'm confused here when you said this "But this would be fixed if use is made of VTFCmd's PSD support regardless" don't you mean "AutoVTF's PSD support" ?
> > 
> > 
> > As was explained here [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2119045633) VTFCmd does have undocumented PSD support, I confirmed this on old VTFEdit by selecting PSD with All Formats
> 
> Oh interesting. Okay, I did some testing and here's what happens:
> 
> I made this in Photoshop:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333016034-88ed6cf6-f40c-401e-a1ce-f21d4ada318e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTYwMzQtODhlZDZjZjYtZjQwYy00MDFlLWExY2UtZjIxZDRhZGEzMThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZDI2ZTBhOTY5NzlkNGY3OWMzMThiZDU5YTdjOTgxNjg4OWU0MzU5MDdhNjQ0MTAyM2RhNjQxNjQ2MjFiZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mTXghYs4JWM_Zdza6NsDw1xyj8mYb_jN1vCyxuBVkho)
> 
> Saved it as 32bits/pixel TGA:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333016084-e4529e2c-6d49-4a88-b3c3-43fe1fea930d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTYwODQtZTQ1MjllMmMtNmQ0OS00YTg4LWIzYzMtNDNmZTFmZWE5MzBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDZmZGY0YzBlMzQ0ZjM1MjU0ZTE3ZGU2NmY0MTBiMTk0M2Q4NmQ2NzE5ZjBhOTY5ZGM2ZjIyZjMwNjlhZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVwtdJfGiJQYaN4Zit7WJ73NKXkPGwMOjjBPIzIRvDE)
> 
> And when I import it back into Photoshop, I saw that the TGA itself just doesn't have any alpha information:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333016176-e98b98cb-3f95-433b-974b-6210904bda85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTYxNzYtZTk4Yjk4Y2ItM2Y5NS00MzNiLTk3NGItNjIxMDkwNGJkYTg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDZkOGI0MmQxMTI3NWY5NmVjZGViNTk4MTc5Y2NlNzUwYjAzODcxMThkMzRlZWE1MDFkYjRkZmU2YzY5Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SvM8bYE4mNNLwJykIvYvC0Uy2slgU5V6gMk-y9TgETA)
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333016210-ff0ab7e3-265c-426a-95db-7b6c7e7483f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTYyMTAtZmYwYWI3ZTMtMjY1Yy00MjZhLTk1ZGItN2I2YzdlNzQ4M2Y1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjFmOTM5ZGRhNzJhY2FmNGRlMjZiYWMzNjliZGVlN2RmMDFmMmZhYjE3NGI1ZmUxMzA2YTk1YTdmMTk5OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUCocTsyGtAYNNP0OzljCwiphhejC_wzKAsf6D2sEZ8)
> 
> Confirms what [MARK2580](https://github.com/MARK2580) said here: [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123696810)
> 
> But, If I go back and don't save it as a TGA, but as a PSD instead:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333016583-bde40fad-d1aa-44a1-92b0-2ddca4f6b5f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTY1ODMtYmRlNDBmYWQtZDFhYS00NGExLTkyYjAtMmRkY2E0ZjZiNWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMWMyYTIxYmRkYWM5NzFkODNmYWE2ODYzNGY5NjVkZWMyNGFjZjEyYjhlMDQ3YjJkNjYxZGY0ZmZmNThmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JioOo37zrdgo6wg-UGqB-2lJipDdJ_jMjzufbToKAbw)
> 
> And then feed that PSD into AutoVTF:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333017002-ce1b3bc3-9286-4dd2-b89c-a6612f22fff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTcwMDItY2UxYjNiYzMtOTI4Ni00ZGQyLWI4OWMtYTY2MTJmMjJmZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMTNmNmVkMzc3OTdkZjQ2NGQyYmNkNGI1MTA4YTQzOWIzN2NiOGU3MTQ0NmFmYzczYjU1OGM3ZWM1Njk4NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Q9BpbV70GrwQ6qCTg_32bc5VAdwXAlyr2tAXpQ6OoQ)
> 
> Then, in the VTF it actually has alpha
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333017050-526478a8-0559-4dc3-9e92-af0b89c5d092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTcwNTAtNTI2NDc4YTgtMDU1OS00ZGMzLTllOTItYWYwYjg5YzVkMDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwOGNlMWNkYThjYmNiMGEwODllYzBmYTNiMzA3NDE2OTRkZTRlYjk2M2U4YjdlN2EzZmM1NjE2MWU3YzdkNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8rAsjFMMXMwTZppr05uwtdXZqFyCFR02N7pp0NpcSwY)
> 
> It's an issue with Photoshop _itself_ somehow not being able to keep alpha when exporting to TGA... Which is very weird.
> 
> Internally, the program uses ImageMagick to convert PSD to TGA, which then is converted to VTF by VTFCmd. So the alpha must be correctly exported in this case. So it seems like you shouldn't have a problem, but you do though. Can you describe your process like I did?
> 
> Also please say version you are using, it's shown in the title:
> 
> ![image](https://private-user-images.githubusercontent.com/56874047/333017691-b883b287-9ce6-4ef7-a3ea-52fed11e351f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzUwMzYsIm5iZiI6MTcxNjQzNDczNiwicGF0aCI6Ii81Njg3NDA0Ny8zMzMwMTc2OTEtYjg4M2IyODctOWNlNi00ZWY3LWEzZWEtNTJmZWQxMWUzNTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDAzMjUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZTFmNmM0NDI2YmZkNmM4ZDk2YzY1NTBlMmI1NWVmMDQwZGFiMDUyOTg5NTViYzQxZGU2ZGFlMTc0ZDY4NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXI-RL3mzXL_8ZX25GwJEQX4sXCIVFoEt5YOF-KBx-Q)

You are trying to save a TGA and PSD with layer transparency, not an alpha channel. Photoshop handles these separately. Each layer has its own RGBA channel, but it does not contribute to an actual alpha channel, which is used separately. The problem with using layer transparency is that it causes matting issues, or white fringing / haloing around the edges of the image. 

This is because these programs usually remove the RGB color from pixels with an A of 0 to save on file space. When read again, this RGB value has to be restored, and it's usually interpolated as white. You will notice if you disable masked view on your example texture, where there was transparency it will be white. This isn't really an issue for regular photos. But for masked game textures, this leads to problems because the edges of a texture will blend into the color white before it becomes totally transparent. 

![tga](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/2a7a7e60-ebcd-4fba-8a86-9a73a261b340)
![tga1](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/8d1fd836-3950-435b-a626-e896b1d489ca)
![tga2](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/57b18b92-d287-4dab-bcb0-5eeb89774d0c)
[gtav_grass.zip](https://github.com/NvC-DmN-CH/AutoVTF/files/15411430/gtav_grass.zip)

**Comment by MARK2580** [comment]
> Confirms what [MARK2580](https://github.com/MARK2580) said here: [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123696810)

This is some weird Photoshop bug. If, for example, your initially opened file was in PNG format, you will NEVER be able to save it in TGA 32bit. I have been “burned” so many times because of this, I drew an alpha mask, saved it without checking it, closed the file, and then it turned out that all the work was gone .
For such cases, I have set up scripts for converting formats using NConvert. It can be useful to convert png to tga, thereby obtaining an alpha channel, the place of transparency.

**Comment by MykhailKozak** [comment]
> > Confirms what [MARK2580](https://github.com/MARK2580) said here: [#4 (comment)](https://github.com/NvC-DmN-CH/AutoVTF/issues/4#issuecomment-2123696810)
> 
> This is some weird Photoshop bug. If, for example, your initially opened file was in PNG format, you will NEVER be able to save it in TGA 32bit. I have been “burned” so many times because of this, I drew an alpha mask, saved it without checking it, closed the file, and then it turned out that all the work was gone . For such cases, I have set up scripts for converting formats using NConvert. It can be useful to convert png to tga, thereby obtaining an alpha channel, the place of transparency.

Doesn't seem to be a thing in CC 2015 at least. What it looks like is that when you open a different file format, when you go to save as TGA, Alpha Channels is disabled automatically. This just needs to be checked and it should be fine, otherwise, maybe try a different version of Photoshop.
![333028944-8d1fd836-3950-435b-a626-e896b1d489ca](https://github.com/NvC-DmN-CH/AutoVTF/assets/34525721/d2121371-0b6d-4ab7-a943-2db39557e004)

**Comment by MARK2580** [comment]
> What it looks like the problem is, is that when you open a different file format, when you go to save as TGA, Alpha Channels is disabled automatically. This just needs to be checked and it should be fine, otherwise, maybe try a different version of Photoshop.

This is exactly what I’m talking about, if you open something other than tga, there is a high probability that the alpha will not be saved, even despite this checkbox and the choice of 32 bits. I have already used three different versions of CS6 / 2019 / 2022 and had this problem in all of them.

**Comment by MykhailKozak** [comment]
> > What it looks like the problem is, is that when you open a different file format, when you go to save as TGA, Alpha Channels is disabled automatically. This just needs to be checked and it should be fine, otherwise, maybe try a different version of Photoshop.
> 
> This is exactly what I’m talking about, if you open something other than tga, there is a high probability that the alpha will not be saved, even despite this checkbox and the choice of 32 bits. I have already used three different versions of CS6 / 2019 / 2022 and had this problem in all of them.

I've never had this issue, or know any one else out of the dozen or so other devs I know who've had this problem, so I don't know what to tell you.

**Comment by NvC-DmN-CH** [comment]
I am also confused, sorry. The issue will remain open for discussion

**Comment by MykhailKozak** [comment]
> I am also confused, sorry. The issue will remain open for discussion

https://www.youtube.com/watch?v=-q4OFId5sHc

Hoping this video will be enough to explain the issue and what's going wrong. Otherwise I'm not sure how else to put it. 
Sorry it's been a text fiasco this whole time, I should have just opened with this since I suppose it's a fairly advanced texture topic.

**Comment by NvC-DmN-CH** [comment]
> > I am also confused, sorry. The issue will remain open for discussion
> 
> https://www.youtube.com/watch?v=-q4OFId5sHc
> 
> Hoping this video will be enough to re-explain the issue and what's going wrong. Otherwise I'm not sure how else to put it. Sorry it's been a text fiasco this whole time, I should have just opened with this since I suppose it's a fairly advanced texture topic.

Oh, try the newest version that I just pushed (1.2.1) I may have unintentionally fixed the issue you are describing as well.

Thanks for the video explanation btw, I appreciate it lol.

Hmm... I could try looking into automatically filling the color channel with "extended" color where the alpha is 0, like what happens inbetween UV islands when you bake textures in blender
