### ISSUE TITLE
Alpha channel gets lost in VTF -> TGA conversion!

### ISSUE THREAD

**Issue by NvC-DmN-CH** [NvC-DmN-CH/AutoVTF#9]
It seems like VTFCmd is at fault here, because it is responsible for VTF->TGA conversion. Since I don't have much experience with C yet, I'll need some time to investigate what exactly is happening to try to fix it, sorry!

**Comment by DBONKA** [comment]
Tested converting VTF with Alpha to TGA using AutoVTF, TGA still had the Alpha channel after the conversion.
But converting PSD with Alpha into VTF loses the alpha channel (opened a separate issue for that)

**Comment by NvC-DmN-CH** [comment]
nevermind, i fixed the issue, will update soon
